carpentries/instructor-training

02-models.md

I'm taking the instructor training and noticed this broken link

fixing transposition of link in markdown

---

trainer-guide-2-day.md

This schedule looks very detailed and rigid but should help new trainers work out how to plan the 2day f2f workshop and split the material.
This is only an initial stub. I'd suggest to split trainer's guide as it is now (http://swcarpentry.github.io/instructor-training/instructors.html) into separate guides for different forms of deliver (multi-week online; 2day online and f2f online).

Adding detailed trainers guide for 2day f2f workshop

---

10-carpentries.md
messages/training-checkout.md

Spun off from [this sub-thread][0].
Try to head off PR and commit-message summaries that don't tell the
lesson maintainer what the change is about, or why the submitter
thinks it's a good idea.
I've put an abbreviated form of this comment in the training-checkout
reminder, with an fully qualified link to more detailed 10-carpentries
entry.  The messages/ entries look like email templates, neither a
relative link (which wouldn't resolve) or a detailed description
(which would be distracting) seem like good fits there.  If the
messages/ entries are email templates, I'd suggest injecting some [YAML
front matter][1] so we can use:
{{ site.domain }}{{ site.baseurl }}/10-carpentries.html#final-steps
in that link.  But that seemed like a bigger change than I should be
biting off in one commit.
I …

10-carpentries: Remind learners that describing and motivating PRs is important

---

_episodes/20-practices.md

Closes #138.
Also fixes some formatting in the description list: no reason to italicize terms.

Mentioning the peak rule

---

_episodes/07-memory.md
_episodes/17-motivation.md

A pair of cross-links between the "Expertise and Memory" and "Motivation and Demotivation" lessons was out of date.

Update links between memory and motivation lessons

---

_episodes/17-motivation.md

When refering to Margolis and Fisher, the parenthesis was left open, leaving the reader to think that the under-representation of racial group was actually part of the reference.

Add a missing closing parenthesis in Motivation and Demotivation

---

_extras/guide.md

This adds suggested feedback items for the live-coding exercise, these can be used in the etherpad to collect input from learners. From the 2016-05-18 online workshop.

Add feedback suggestions for live-coding exercise

---

_extras/checkout.md

This change was made in response to @ErinBecker's last comment about being DC or SWC specific for checkout, as described in [PR #216](https://github.com/swcarpentry/instructor-training/pull/216)

clarified DC SWC checkout requirements

---

_includes/navbar.html

If accepted this pull request will add a "hamburger" menu for small screen devices, fixing https://github.com/swcarpentry/instructor-training/issues/235

add standard bootstrap menu icon for small screens

---

_episodes/08-memory.md

We had some asterisks in the rendered version. This should fix that.

Fix non-italics word in sentence in italics

---

_episodes/19-motivation.md

what-to-teach.png is not a 2x2 plot. This adds a bit of clarification to the exercise. The alternative is to redraw the plot as a 2x2 grid.

Clarifying 2x2 plot (grid)

---

_episodes/15-carpentries.md

Addresses #261. However, for Software Carpentry only, as the Data Carpentry lesson links actually refer  to multiple repos each with their own github repo and instructor guide.
No fancy icons, though, not sure how to get them added. As pngs?

Made list of SWC lessons into a table

---

_extras/exercises.md

noticed that links were lost in `_extras/exercises.md`. 
It looks like links in `_episodes/` were updated in #267  , but not on in this directory.

Fixed links in _extras/exercises.md that were lost.

---

_extras/checkout.md

Based on some feedback from a instructor trainee, there is a danger of confusion when trainees need to choose a lesson to teach from. For SWC all is well, what is a lesson and an episode is clear from the webpage. For DataCarpentry, however, the situation is a bit more blurry. http://www.datacarpentry.org/lessons/ lists workshops which each have lessons. But, for example, the R-genomics lesson http://www.datacarpentry.org/R-genomics/ has its episodes called `lesson 00`, `lesson 01` etc. Perhaps we need to ask DC to adjust that. 
At any rate, this PR adds an example lesson and segment that trainees may be asked to demonstrate for both SWC and DC.

Checkout: add teaching demo lesson/segment examples

---

_episodes/03-terms.md

I think the urls are missing "instructor-training".

Links to Key Reading .pdf are broken.

---

_episodes/19-lessons.md
_episodes/21-carpentries.md

It appears that indirect URL refs in Markdown pages that use variable expansion don't work, so this PR uses inline.
Thanks, Jekyll.
Replaces #305.

Fixing broken links.

---

_episodes/19-lessons.md

In the _lessons_ episode, a link to one of the papers has a typo in the formatting.
I also changed the base url variable so it would work correctly for instances not hosted through GitHub Pages (the `{{page.root}}` syntax is used elsewhere in the repository).

Correct link formatting and syntax

---

_episodes/15-practices.md

During our instructor training session (https://allegravia.github.io/2017-02-21-online-instructor-training/) a problem was highlighted in that some people didn't know the definition of the acronyms VPS and SSH. Perhaps links to these would be relevant?

Define the VPS and SSH acronyms in the Carpentry Teaching Practices document

---

_extras/guide.md

The current link goes to the raw markdown file that looks horrible. This PR links to the rendered version on github.

Link to rendered version of teaching demo rubric

---

_extras/guide.md

Trainers should not certify people from their own institution or from the workshops they taught. Addresses #332 and more.

Clarify not to certify certain trainees

---

_extras/checkout.md

Fix formatting error for email contact in "Please note that:" section of Part 1 instructions.

Fix email contact link, replace ] with )

---

_extras/guide.md

As per agreement with Trainers group and Carpentry staff, a single checkout will now be required to certify for both Data and Software carpentry.

Change to single checkout

---

_episodes/13-live.md

Fixes issue https://github.com/swcarpentry/instructor-training/issues/414, at least in the main lesson page.

Add reminder about closed captioning

---

assets/js/lesson.js

Addresses https://github.com/swcarpentry/instructor-training/issues/435
Makes it so that challenge text shows by default, rather than needing to be clicked to appear.
Removes the reference to '.challenge' in assets/js/lesson.js

changed default behavior for how challenges show

---

assets/js/lesson.js

Related to https://github.com/swcarpentry/instructor-training/issues/435
Also makes it so that Discussion sections appear by default, rather than click to open.

made discussion sections also appear by default

---

_episodes/21-carpentries.md

Update the "Who Can Teach What" section to reflect the changes made in the instructor checkout procedure concerning certification for Data Carpentry vs. Software Carpentry.

Update certification policy

---

_episodes/13-live.md

Turns out @gvwilson maybe made that term up. But Jon Udell used the term "tacit knowldege" (originally derived from Michael Polanyi: http://press.uchicago.edu/ucp/books/book/chicago/T/bo6035368.html) to refer to this exact thing. This edit still preserves the term "lateral knowledge transfer" (because it's neat!), but also points to its provenance in the link that was added.

Point to a reference for "Lateral knowledge transfer"

---

files/rubric.md

The rubric was embedded in the application form, which was plain text. Converted to markdown to make easier to read and extracted rubric items to top of document. 
Added note that, although this version of the application was approved by the Trainers group, it has not yet been implemented (as of 5/15/17).

Update rubric for instructor training applications

---

_episodes/11-load.md

an extra `>` was throwing out the parser to format the last challenge correctly

fix formatting of challenge in cognitive load lesson

---

_episodes/21-carpentries.md

Remove exercise on critiquing pre-assessment. Most of our trainees don't have experience with assessment and any changes they would propose anyway would need to go through our IRB process to take effect. In addition, we don't want to chance our assessment tools frequently, as that makes it difficult to compare with previous responses. 
This fixes https://github.com/swcarpentry/instructor-training/issues/379

remove exercise

---

_episodes/21-carpentries.md

This information is in the checkout module and up to date there.
Fixes https://github.com/swcarpentry/instructor-training/issues/456

remove paragraph on debriefing

---

_episodes/01-welcome.md

Software Carpentry were duplicated. Might also make sense to  just say "Carpentry activities" after the merger

Fixed typing error

---

CONTRIBUTING.md
README.md
_config.yml
_extras/guide.md
_extras/partner_policy.md
_includes/links.md
bin/lesson_initialize.py
files/messages/checkout.txt
files/messages/welcome.txt
files/rubric.md
setup.md

Change all hard-coded links from swcarpentry.github.io/instructor-training to carpentries.github.io/instructor-training. Also changes links to github.com/swcarpentry/instructor-training to github.com/carpentries/instructor-training. 
Hope that this will solve redirect issue.
@tracykteal @maneesha @rgaiacs @ChristinaLK Could you please review and merge?

Fix redirect

---

_config.yml
index.md

Adding redirect from http://swcarpentry.github.io/instructor-training/ to http://carpentries.github.io/instructor-training/

Add redirect

---

_episodes/20-carpentries.md

Fixed minor typo

---

_episodes/20-carpentries.md

There were a mix of `.` , `:`, and `,` in the line endings for each item in the list. 
This change makes items with sub-lists end in `:` and items that do not to end in `.`

Unify list endings

---

_includes/workshop_footer.html

Similar to lesson_footer.html, copyright should continue until this year.

Updated workshop footer copyright

---

_episodes/20-carpentries.md

If I understand correctly, instructors don't provide SWC with the assessment results; rather, SWC provides the instructors with the results. The instructors' obligation is to make sure learners fill out the surveys.
pointed out by @maneesha during SWC Instructor Training

Clarify the instructions about assessment results

---

_episodes/15-live.md

It seems to me there should be a good way to do this using templating,
but the current way this is done results in a broken link.

Fix a broken link to another part of the lesson.

---

_episodes/02-practice-learning.md

Currently, the list of books by Patricia Benner is an Amazon link.
I think it would be more reasonable to link to a general catalogue of books (WorldCat seems exhaustive enough) and let the reader choose their preferred seller, rather than directly providing them with a link to a specific seller we might seem to give preference to.

WorldCat link rather than link to specific seller

---

_episodes/14-lesson-study.md

this is probably a left over from the translation of the lesson from python, and not needed. In R, calling a variable at the terminal defaults on the print method.

remove print statement

---

_extras/guide.md

Reverts carpentries/instructor-training#555
Markdown broken at end.

Revert "add email template for bilingual demo sessions"

---

_episodes/15-live.md

Addresses https://github.com/carpentries/instructor-training/pull/516#issuecomment-335293372: moves the top ten tips back to the main text and removes the short summary at the end of the lesson.

Return Top Ten Tips to main text

---

CONTRIBUTING.md

The [issues] link, defined at the bottom of the page, needed to be updated from:
https://github.com/swcarpentry/instructor-training/issues/
to:
https://github.com/carpentries/instructor-training/issues/

Updated issues links

---

_episodes/22-practices.md

This updates the relevant section of the instructor training with the new `@carpentries.org` email addresses for follow-up to code-of-conduct violations occurring during a workshop. (https://github.com/carpentries/instructor-training/issues/567)

Update emails for reporting code-of-conduct violations

---

_episodes/15-live.md

responding to consensus on https://github.com/carpentries/instructor-training/issues/598 . Also removes descriptions from links as these are hopefully unnecessary.

change "bad" to "compare contrast"

---

setup.md

This pull request links the text
> If you are interested in doing more reading, we have some recommendations
to this link: https://carpentries.github.io/instructor-training/reference
Previously, this link was https://carpentries.github.io/instructor-training/reference#Books which did not work

Use correct URL for SWC books

---

_episodes/20-carpentries.md

Fixed an inappropriately formatted link in the list of ways to participate in the community (Lesson Maintainers) and hopefully corrected a broken link to the license.

fixed broken links

---

_episodes/20-carpentries.md

Now that the Data Carpentry workshop template repository is deprecated, I removed mention of it in this lesson. I also removed "SWC" to avoid confusion. The workshop template is the same for all types of workshops (SWC, DC or LC). There is a variable to set in the template to get the type of workshop needed.

remove link to DC workshop-template

---

_episodes/20-carpentries.md

Hi there,
The licensing link was broken on this page. This is a simple fix to correct it.

Fix license link.

---

_episodes/08-motivation.md
_episodes/11-practice-teaching.md
files/messages/welcome.txt
reference.md

in reference to issue https://github.com/carpentries/instructor-training/issues/544 I have gone through and updated the amazon links to now point to WorldCat

Amazon to worldcat

---

reference.md

The DOI foundation recommends [this new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8) ;-)

Hyperlink DOIs against preferred resolver

---

_episodes/20-carpentries.md

In addition to https://github.com/carpentries/instructor-training/pull/699 changes, updated overview to include Library Carpentry.

Updated overview to include Library Carpentry

---

setup.md

The "Starting with Data in Python" link is wrong. It contains "01" when it should contain "02".

Fix "Starting with Data in Python" link.

---

README.md

Names of Christina Koch and Erin Becher pointed to outdated SWC and DC pages, and no link for Karen Word was provided. Now linked to team/instructors page in Carpentries website.

Fixed links to maintainers in Carpentries.org

---

files/teaching-demo-rubric.md

Step 1 to address https://github.com/carpentries/instructor-training/issues/657
This PR is intended to prepare the demo rubric for use within the instructor training curriculum, as well as making it more useful to Trainers, particularly those who are new to running teaching demonstration sessions. 
This change:
- adds information about low failure rate to counter fears of trainers and trainees, most of whom have been traumatized by high-stakes testing. 
- simplifies language in the rubric to make it easier to read 
- adds positive actions to two negatives that previously lacked clear opposites
- modifies the note-taking form to directly and sequentially follow the rubric

Clean up demo rubric for addition to curriculum

---

_extras/guide.md

Because all of the information here has been duplicated in the Handbook, these notes are now free to focus exclusively on details that are necessary or helpful in preparing for an Instructor Training workshop.  This PR establishes a new structure for this page -- will fill in Curriculum Teaching Tips section after any restructuring associated with the current update is complete.
This also incorporates several changes proposed in https://github.com/carpentries/instructor-training/pull/714 and is intended as a replacement for that PR.

Overhaul notes to focus on workshops only

---

_episodes/05-memory.md

- replaced all but one instance of working memory with short-term memory. 
- moved "persistent" to a description
- renamed the title to "memory" rather than  "working memory"
relates to https://github.com/carpentries/instructor-training/issues/741

update memory terms

---

_extras/guide.md

This is one item that Trainers may look for here on short notice, and it's not clear from the handbook link that these are located in the Trainer Guide.

Add direct link to demo instructions

---

_episodes/23-checkout.md
_extras/checkout.md

The links to demo-recovered etherpad have never been updated. This PR fixes that.

update link to demo etherpad

---

_episodes/20-checkout.md

With the EC elections in mind, I thought it would be nice to let incoming instructors know about their voting privileges. Bundled this in with a small new section on the overall benefits of a badge.

Add info about badge privileges

---

_extras/guide.md

fixes broken link as per https://github.com/carpentries/instructor-training/issues/827

update link to slides folder

---

_episodes/03-expertise.md

added the perma link suggested here: https://github.com/carpentries/instructor-training/issues/888#issuecomment-465354657. closes #888

update link to chicago tribune paper

---

_episodes/18-management.md

Existing order creates a major problem with CoC discussion last -- it ends up crunched for time and leaves everybody on edge as they head off to lunch. This PR moves management challenges and CoC up to come before co-instruction. This allows both of these topics to carry forward into conversations about co-instruction, and leaves an easier choice for cutting content to get to lunch on time.

Change activity order in Management

---

_episodes/09-mindset.md

hmm. there was a weird typo as pointed out by @gcapes in https://github.com/carpentries/instructor-training/issues/89/ ... maybe it was an emoji at one point, but not it was just a strange character or space. I removed it.

remove strange character

---

_extras/guide.md

Given the discussion in https://github.com/carpentries/instructor-training/issues/540, this PR adds a note about flash not working for everyone. 
(I meant to include this with my change in https://github.com/carpentries/instructor-training/pull/915, but my github skills are not cooperating today).

add note about flash to guide

---

_episodes/05-memory.md

As per discussion in https://github.com/carpentries/instructor-training/issues/540, this PR reverts to the old memory test.

revert memory test

---

_episodes/09-mindset.md

In issue https://github.com/carpentries/instructor-training/issues/892, @gcapes notes that error framing is not defined or explained. I tried to google a definition of error framing, but I could not find a website with a definition. There is a brief definition in [our glossary](https://carpentries.github.io/instructor-training/glossary/index.html), so I added that sentence into the lesson. 
Maybe someone has a reference to add? @ErinBecker @karenword ?

Add error framing definition to mindset episode

---

_episodes/20-checkout.md

Pointed mentoring groups to handbook rather than carpentries website.

Fixed link to mentoring groups

---

_episodes/15-lesson-study.md

Heading included SWC and DC. Removed so that it says *Evaluate Learning Objectives* rather than *Evaluate SWC and DC Learning Objectives*.

Removed lesson program language from heading

---

_episodes/05-memory.md

Previous attempt misdirected to glossary; this should correctly send to previous (flash-challenged) exercise.

Reverts memory test link

---

_episodes/09-mindset.md
_episodes/13-second-welcome.md
_episodes/20-checkout.md
_episodes/21-carpentries.md
_extras/guide.md
index.md

GitHub and Etherpad were already the capitalizations used in the majority of cases; this adapts the few deviating cases.

Fix typos; standardize capitalization of GitHub and Etherpad.

---

files/rubric.md

This should render more nicely ;-) Only `*` without indentation keeps the "recruitment areas" on the uppermost list level.

Improve list formatting

---

_episodes/18-management.md

The Code of Conduct Committee now collects incident reports through a secure form. Updating the instructor training to reflect this change. I'd be grateful if either of the maintainers reviewed and merged this change so that it is consistent with what is in the handbook.

Revised avenue for reaching the Code of Conduct Committee

---

_extras/demo_lessons.md

This creates a table of all the Spanish episodes. Copied from the English lessons above and updated with the titles and hyperlinks to the Spanish lessons

add  Spanish lessons to suggested demo episodes

---

_extras/demos_rubric.md

We say they do not need to complete the checkout process in any particular order, so I removed "final stages" from the language of the rubric.

Removed language about "final stages"

---

_episodes/20-checkout.md
_extras/checkout.md

Added text to the checkout episode (in addition to the checkout page in Extras which may now be redundant?). Also suggest repositioning text to resolve some language redundancy/flow.

Karenword patch 5

---

_extras/demos_rubric.md

Added a link to each page on the other page, just so it's easier to cross-reference in a hurry.

Cross-referencing rubric and demo pages

---

_extras/checkout.md

In the step 3, the link to the Etherpad direct to a non-working pad (not loading). In the chat of that pad is the link to a new, properly working pad. I put the new link to the working etherpad.

Fix demopad link

---

_episodes/20-checkout.md

Markdown is depressingly sensitive to spaces in its ordered lists. Converted the sub-list from an intended outer numbered list to an inner numbered list so it's 1. 1.i.

Fixing sub ordered list to proper markdown

---

_episodes/01-welcome.md

Needs to be:
https://carpentries.github.io/instructor-training/icebreakers/index.html
instead of:
https://carpentries.github.io/icebreakers/index.html

Fixed broken link to icebreaker questions.

---

_episodes/20-checkout.md
_extras/checkout.md

Updating links to demos pad in checkout episode and extras document. (I hope that's all of them!)
New pad: https://pad.carpentries.org/teaching-demos

Updating demos pad links

---

_episodes/05-memory.md
_episodes/21-carpentries.md

The `po` files are the tokenised version of the lessons. The tool we are using complains if the following *typos* or empty lines at the end of sections are not fixed.

[translations] Clean lessons to create po

---

_episodes/01-welcome.md

This didn't give the correct link for a local build,
even though it gets magically fixed for github pages.
It gave an extra 'instructor-training' in the path.

Fix link to icebreakers

---

_episodes/21-carpentries.md

Included Library Carpentry when talking about Software and Data Carpentry lesson format. An alternative would be to use "The Carpentries' lesson format", to include all current and future lesson organisations. and avoid the need to updating this.

Included Library Carpentry when talking about lesson format

---

_episodes/06-feedback.md

update the links for the surveys (see [this blog post](https://carpentries.org/blog/2019/10/transition-to-typeform/) for more context)

Update survey links

---

_episodes/21-carpentries.md

provide a little more details (and re-organize) section about how to set up and name workshop websites.

provide more instructions about for workshop website

---

_config.yml
_episodes/20-checkout.md
_extras/checkout.md
bin/boilerplate/_config.yml
index.md

AMY seems to have moved from https://amy.software-carpentry.org to https://amy.carpentries.org. Fix links accordingly.

Fix AMY links to point to amy.carpentries.org.

---

_episodes/01-welcome.md

There is no local variable to the page `training_site` it is set in `_config.yml` and scoped to `site.training_site`. Should fix the link.

Fixing broken link

---

_episodes/03-expertise.md

I don't know what I'm doing in GitHub, sorry. Just trying to tidy up some of the wording in this lesson. This lesson explicitly says "we prefer not to use the phrase 'blind spot'", but  then goes on to use that phrase. I've suggested some alternative wording.

Reworded "blind spot" to "expert awareness gap"

---

_episodes/12-homework.md
setup.md

Link to episode _Repeating Actions with Loops_ for python-novice-inflammation is broken in [Setup](https://github.com/carpentries/instructor-training/blob/gh-pages/setup.md).
Replace `02-loop`  with `04-loop`
Link to episode  _Repeating Actions with Loops_ for python-novice-inflammation is broken in [homework episode](https://github.com/carpentries/instructor-training/blob/gh-pages/_episodes/12-homework.md).
Replace `03-loop`  with `04-loop`
Related to #1087

Fixed link to python-novice-inflammation episode

---

_extras/guide.md

This adds instructions and a link to a Topicbox message on the (now private) Trainers list that has the Host code for Zoom rooms 2 and 3.

Add link to message with Zoom Host code

---

_episodes/20-checkout.md

The [checkout page in extras](https://carpentries.github.io/instructor-training/checkout/index.html#lesson-change) lists possibly types of contributions, starting with the type that we are most encouraging from trainees. This modifies the same list in the lesson episode proper to match the order in the extras file.

Switch order of recommended contribution types

---

_episodes/18-management.md

Addresses https://github.com/carpentries/instructor-training/issues/1108 -- while this context may differ from that in our Handbook, I think it is probably best to remove the suggestion that Instructors demand an apology. This is not an especially useful strategy (at best) and the appearance of inconsistency is a problem.

Remove "ask to apologize"

---

_extras/training_calendar.md

Adds a 4 week long event in Australia Eastern Standard Time
Reorganizes sections and text to not refer only to two day events.

Add AEST event, re-organize page

---

_episodes/05-memory.md

Just a small edit, the link is dead for the Kirschner paper.
Lots of link options [here](https://scholar.google.com/scholar?oi=bibs&hl=en&cluster=11065780712206344145), not sure what is preferred.

fix link to kirschner paper

---

_episodes/20-checkout.md
_episodes/21-carpentries.md
_extras/checkout.md

1. include Incubator lessons and Glosario in list of repositories valid for checkout
2. direct trainees to Help Wanted page to find a way to contribute
3. create a list of eligible repositories for the contribution step of checkout, link to this from body of lesson - a single point of reference should make it easier to maintain this list.

Mention Help Wanted page and Glosario for checkout

---

_extras/checkout.md

Cleaning up my own mess! This fixes a broken link to the Glosario GitHub repo.

fix link to glosario

---

_episodes/12-homework.md

The link was broken, removing the 'static' prefix fixes it.

Fix broken link

---

_episodes/21-carpentries.md

I think this is the last page that still had broken links due to the carpentries url changing to no longer have "static"

fix urls by removing static prefix

---

_episodes/06-feedback.md

Addresses #1078 by including links to the text-only version of the surveys to make it easier for workshop participants to have an overview of the questions asked without having to answer the questions.

[fix #1078] include links to text-only survey previews

---

_episodes/09-mindset.md

The testimonial element only shows up as a pink box without the header. With the header, it's more clearly denoted as a testimonial.

add title element to testimonial

---

_episodes/20-checkout.md
_extras/checkout.md

I think this addresses the two issues mentioned to note that community discussions have different formats and that some demos are focused. 
@maneesha your input on the language re: demos would be helpful

note sessions with themes or community focus, closes #1193 #1189

---

_episodes/02-practice-learning.md
_episodes/05-memory.md
_episodes/11-practice-teaching.md
_episodes/15-lesson-study.md
_episodes/21-carpentries.md

This PR is my attempt to add alternative text to all images in the lesson. I've tried to follow the guidelines in [this guide from Harvard's digital accessibility office](https://accessibility.huit.harvard.edu/describe-content-images). I am by no means claiming these are the perfect alt texts to have for each of these images, and welcome additions/clarifications/changes. In particular, the two images in 21-carpentries.md (a timeline and a Venn diagram) were challenging, as was the Bloom's taxonomy diagram. We should probably have that information summarized in text form in the lesson body, not just in alt text. I hope however that these additions get us a step closer towards making our lessons accessible to the Blind and visually impaired.

Add alt text for all images

---

_episodes/15-lesson-study.md

taught last week with having trainees focus more on the episode they're teaching from.  I think it worked well. In particular I didn't have trainees complain that this exercise was too hard or not enough time was allocated, and I didn't extend the time. Their analyses were more reflective and their follow up questions lead to deeper discussion and questions about formative assessment again, instead of getting stuck on blooms only. 
I think when we leave it open for them to choose, trainees spend a long time looking at different lessons and episodes within them to choose a learning objective.  By directing them to continue where they are, they can focus on the learning objective and applying Blooms.

Focus learning objective study on single episode

---

_episodes/20-checkout.md

Fixes https://github.com/carpentries/instructor-training/issues/1203
(If we want to add this back as homework we can always do that later, but this correction is consistent with status quo).

Remove homework reference

---

_extras/guide.md

Related to [this PR](https://github.com/carpentries/carpentries.org/pull/1012).  I updated the link so they have to make a template copy of it and it is less likely someone will accidentally edit the form.
@tobyhodges also updated the form to take into account that folks will get to it via this updated link.

Changing min card template to preview template link

---

_extras/checkout.md

This is mostly important for the link to the community discussion pad, which currently links to a page that doesn't support HTTPS (before redirecting to another domain that supports HTTPS). Therefore, this causes issues in browsers that are configured for HTTPS-only navigation.

Update links to HTTPS

---

_extras/training_calendar.md

Adds 2021 Q4 training events.
Based on conversation with @karenword  @klbarnes20 @talishask today, the calendar listing is also generally re-organized to list all events together rather than sorting by event duration and time zone.

updates and reorgs training calendar for 2021Q4

---

_episodes/09-eia.md

correct glossary link closes #1280

---

reference.md

I'm unfamiliar with the page:reference in the yaml header so I don't know for sure that this will work, but it seems like a legitimate way to change the title of the References page to something other than "Books"?

Retitles references page

---

_episodes/18-preparation.md

Added link for Dunning-Kruger effect (from raw file of Episode 2: https://github.com/carpentries/instructor-training/blob/d3100fc08a689fcbbda48622f008eb31d1cc1652/_episodes/02-practice-learning.md), so link is clickable and text is formatted correctly.
<details>
checkout@carpentries.org so we can record your progress. You've completed your contribution
materials, we …

Add Dunning link

---

_episodes/09-eia.md

tpying error was removed under the section ## Systemic Exclusion cogitive load was changed to cognitive load
<details>
about the lesson maintenance process or would like …

fix typo in EIA episode

---

_episodes/04-expertise.md

A few suggested fixes for episode 04-expertise:
1. fixed steps of reasoning for a competent practitioner (around metal models of people with different skills)
The steps described in the text do not match the diagram (of the mental models of novices/competent practitioners and experts) - we either need to change the diagram or the explanation of it. I've changed the explanation but it may be better to modify the diagram to swap nodes E and F in the diagram.
This was issue with the old curriculum as well, but I never got round to fixing it.
2. list consistency improvement

Align text to images in 04-expertise

---

_extras/training_calendar.md

Fix the training time-slot on [March 24-25, 2022](https://carpentries.github.io/instructor-training/training_calendar/index.html#march-24-25-2022) to `2 pm - 10 pm` instead of `2 pm - 8 pm`

fix: modify time slot in training calendar

---

_episodes/18-preparation.md

As an alternative to the proposed change, we could keep the other verb or both (connected by an and).

Remove extra verb

---

_extras/checkout.md

Removed the space in the `mailto:` link. Some browsers features for selecting the email address from a mailto: link resulted in a space being mapped to `%20` when used in a preferred email client.
<details>
materials, we appreciate your time and effort to improve the …

Adjust mailto: link

---

_extras/checkout.md

Remove the blank line in the middle of the "Sign-up and Set-up" paragra[h.

removed blank line in middle of paragraph

---

_extras/checkout.md

TIL GitHub has IDs that are not usernames! Oops.

ID -> username

---

_extras/guide.md

Thought I had left these somewhere, but they were removed in the update. Several people have asked me for examples, so putting them back here for now.

Add concept map examples back to Trainer guide

---

files/rubric.md

Addition of points for teaching centrally organised workshops was approved by Trainers Leadership at April 13 meeting. 
Other changes here reflect prior point structures that have not been removed from automated scoring due to lags in updating our database. We expect continued delays there, so adding these categories back in to the rubric to accurately reflect the current scoring system. (New categories with added points will be scored manually, but it is harder to remove points that have been automatically assigned.)

Update Open Instructor Training rubric

---

_episodes/14-checkout.md
_extras/additional_exercises.md
_extras/checkout.md
setup.md

There are several mailto links that do not conform to CommonMark spec because they have an unescaped space between `mailto:` and the email (see https://github.com/ropensci/tinkr/issues/68 for more details)
If you [look at a markdown document on github with a malformed mailto link, it shows up as raw markdown](https://github.com/carpentries/instructor-training/blob/gh-pages/_episodes/14-checkout.md#instructor-checkout).
The reason why Jekyll doesn't catch it is because it is based on a variant of markdown that is not based on CommonMark. 
This will help me immensely in my conversions of the lesson.

fix mailto links to CommonMark spec

---

_episodes/23-introductions.md

This PR moves the suggested item up in the list to be grouped with other follow-up type things and leave "celebrate" for last. It also adds a bullet for this item. I'm not sure that the list will actually render sub-bullets, so it may be desirable to strip some of the detail here. However, I'm not too concerned at the moment because I think many of these "solutions" boxes will end up being re-done with in-line Instructor Notes in the workbench.

Reorder solutions

---

_extras/demos_rubric.md

The first commit changes the rubric form into a code block in markdown format for easy copying into text editors. The way it was, I did not see an easy way to use it (If there is, it could be mentioned instead of this change).
The second commit adds “Manual typing” to that form, the only point that was missing relative to the table above.

TD Rubric Template

---

_episodes/18-preparation.md

The instructions state to copy the objective and then add it as the first entry of a list right below. That is redundant.

Remove item from list

---

_config.yml
_episodes/01-welcome.md
_episodes/09-eia.md

Looks like this was removed in an earlier commit, but it's still used in lesson plans.

Fix broken code of conduct links

---

_extras/demos_rubric.md

rubric description included Negative column but columns are changed to Content Opportunities for Growth and Delivery Opportunities for Growth

Change rubric description from Negative

---

_episodes/01-welcome.md
_episodes/03-coffee.md
_episodes/06-feedback.md
_episodes/07-lunch.md
_episodes/09-eia.md
_episodes/10-coffee.md
_episodes/11-practice-teaching.md
_episodes/12-homework.md
_episodes/13-second-welcome.md
_episodes/16-coffee.md
_episodes/17-live.md
_episodes/18-preparation.md
_episodes/19-lunch.md
_episodes/22-coffee.md
_episodes/23-introductions.md
_extras/additional_exercises.md
_extras/guide.md

closes #1385 
I did not change episode names to remove "lunch" to avoid breaking links, but maybe we can do that too? but I think I got all of the other temporal references changed to parts instead of two days.

Make time references to 4 parts, not 2 days

---

_extras/training_calendar.md

Adds the following events for the  Q4 calendar
- The Carpentries Online Instructor Training, October 17-20, 2022
- The Carpentries Online Instructor Training, November 8-11, 2022
- The Carpentries Online Instructor Training, November 15-18, 2022
- The Carpentries Online Instructor Training, December 5-8, 2022
- The Carpentries Online Instructor Training, December 19-20, 2022

add events for 2022Q4 calendar

---

_episodes/17-live.md

Suggested update to address #1419 
Could be a little long for an exercise title, but I included 'anticipate' as a way to reinforce the importance of reflection as assessment. Feel free to shorten!

Rename 'up and down' exercise

---

_episodes/21-management.md

As it is now, the co-teaching section is in an awkward position between a section on feedback and an example of sticky situation. This does not make much sense. When teaching this module recently, I moved it to the beginning, precisely in the place where we are already talking about not teaching alone. This worked for me.

Move co-teaching section

---

_extras/checkout.md

Currently instructions for submitting your issue on AMY are under the heading of Alternatives to Github. I am proposing a new heading for clarity.

Clarify AMY submission instructions

---

_episodes/02-practice-learning.md

This fixes an issue where a list item, sufficiently indented, becomes a code block in commonmark-descendent markdown parsers (which includes GitHub's markdown and pandoc)
Thanks to @sstevens2 for finding this discrepancy in https://github.com/carpentries/lesson-transition/issues/13

fix mistaken indent in list

---

README.md

The reference links for the maintainers all go to the same place, which is not great for accessibility and can be kind of frustrating when you want to find a specific maintainer and you have to scroll through the same page over and over. 
Since the instructors page has anchors that represent the GitHub IDs for the maintainers, I've added those to the URLs to make them unique. 
This will also help address the transition to The Workbench: https://github.com/fishtree-attempt/instructor-training/issues/11 and https://github.com/carpentries/lesson-transition/issues/15

README: point maintainer links to their ID

---

config.yaml

This allows the underlying metadata to be accurate

add date created to config

---

README.md

I've replaced lesson-example with sandpaper-docs and given my attempt at providing succinct instructions.
One of the things that the previous README did not do was to describe the toolchain necessary to even run `make`. 
This will address https://github.com/carpentries/instructor-training/issues/1515
Maintainers: feel free to make and accept any changes you wish.

Update README.md to remove old refs

---

episodes/08-motivation.md
learners/checkout.md
learners/training_calendar.md

I am wondering about the link to the Etherpad that had to be replaced here, and whether we are going to find other problems related to that one. I can't recall where those links used to live in the repository. I will merge this promptly because it's important that these links work, but also tagging @carpentries/core-team-curriculum in case of advice!

More links to fix

---

learners/checkout.md

Replaces no longer working `{{page.demopad}}` link with hardcoded etherpad link. Credit to Clifford Kravit for bringing this to my attention.
Need to verify with @zkamvar prior to merging whether this should be hard-linked or should remain as a page link and corrections made to ensure it works properly again.

Update demo etherpad link

---

episodes/01-welcome.md

This moves the figure caption into the correct syntax to be recognized as a caption:
see https://carpentries.github.io/workbench/transition-guide.html#figures for a comparison and https://carpentries.github.io/sandpaper-docs/episodes.html#figures for an example.

Move caption into figure caption space

---

episodes/17-live.md

The Carpentries do not only teach programming and use participatory live coding to teach other skills as well. Thus, we should not specifically mention programming in the overview question.

Remove 'programming'

---

learners/checkout.md

Add community calendar links where relevant on checkout instructions. Closes #1512 (which changed the file in `/instructors` which no longer exists).

Add calendar to info on checkout

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/suggest_improvement_1_lesson.yml
.github/ISSUE_TEMPLATE/suggest_improvement_2_episode.yml
.github/PULL_REQUEST_TEMPLATE.md

This updates the issue and PR templates to use the language developed by the Curriculum Team, and ensures language about IT checkout is not included.

add in lesson issue & PR templates

---

learners/checkout.md

As the title says, the patch removes the words Welcome session that seem lost between two sentences.

Remove stray “Welcome session”

---

learners/checkout.md

This adds an empty line between a paragraph and the following list. Previously, the list content was rendered as part of the paragraph instead of as a list.

Make framework recognize list

---

episodes/02-practice-learning.md
episodes/04-expertise.md
episodes/05-memory.md
episodes/06-feedback.md
episodes/08-motivation.md
episodes/09-eia.md
episodes/11-practice-teaching.md
episodes/12-homework.md
episodes/13-second-welcome.md
episodes/14-checkout.md
episodes/15-carpentries.md
episodes/17-live.md
episodes/20-performance.md
episodes/21-management.md
episodes/23-introductions.md
episodes/24-practices.md
episodes/25-wrap-up.md

I noticed that the Workbench had positioned some content from the top of each page *above* the lesson questions and objectives. In a couple of cases this kinda worked, but in most cases it really didn't. I changed them all -- in the future we can consider whether we want to exercise the option of positioning a summary of some kind above the questions/objectives box.
@zkamvar FYI in case this affects other lessons - sorry I didn't notice this during the beta!

Fix text in headers

---

episodes/02-practice-learning.md

This quote is not a testimonial. 
Fixing this one only, but note that there may be other errors of this kind, because the prior template did not label the callouts and were sometimes selected based on color rather than strict categorical matching!

correct callout type

---

episodes/20-performance.md

In [the _Round Two_ exercise](https://carpentries.github.io/instructor-training/20-performance.html#round-two) of _More Practice Live Coding_, the text of the link to the rubric for demos still shows the old pre-Workbench URL, even though the link itself points to the correct location. This PR fixes that by updating the link text to match the new target URL.

Update URL in link text

---

episodes/15-carpentries.md

1. Update callout on local help in Carpentries episode to point to the full collection of workshop checklists for local teams (not just helper checklist).
2. Change recommended ratios to be consistent with handbook. If the handbook is incorrect and the original numbers are consistent with current recommendations, this can be returned to 1:8 (in-person) and 1:5 (online) but the handbook checklists should then be updated.

Point to all checklists and make helper recommendations consistent

---

episodes/12-homework.md
learners/setup.md

Add an Excel option to practice episodes to help non-coders with no openRefine experience find a lesson. Also clean up formatting to be treat lessons as one list. Also standardizes names/format/order between setup and homework episodes.

Add Excel option to suggested practice episodes

---

instructors/instructor-notes.md

I offer 2 key changes here. Firstly, to share a template for a teaching demo etherpad. I can't believe I haven't done this before! 
Secondly, the language around the tips is awkwardly passive. I have done a bit of grammatical fiddling to simplify how the tips are introduced.

Add content to the teaching demo tips in instructor-notes.md

---

episodes/11-practice-teaching.md

In this exercise, participants are giving introductions to an episodes, which is part of teaching, but to avoid confusion I suggest to consistently refer to the activity by introduce/introduction.

Replace teach/teaching by introduce/introduction

---

learners/demo_lessons.md

following up from the discussion at [the March 7, 2024 trainers meeting](https://pad.carpentries.org/trainers), this PR updates the list of recommended lessons/episodes for teaching demos to make it explicit that certain lessons within LC and SWC are not eligible for teaching demos in their entirety.

make explicit which lessons cannot be used (english only)

---

LICENSE.md

After #1660 I noticed that it had copyright as SWC. but the current template says Carpenties.

update license to match sandpaper template

---

episodes/12-homework.md
episodes/15-carpentries.md

Thank you @brownsarahm for suggesting  to rename "homework" to evoke less bad memories at #1159 
Based on the pr-requestd label, here is the pull request.
Changelog:
Replaced "homework" with
"preparation.." phrases inthe episode 12-homework
and "practice " in the episode 15-carpentries.
Closes #1159

Rename "homework" to avoid evoking bad memories

---

episodes/01-welcome.md

Instead of linking to CLDT curriculum, link to CLDT description page, which includes information on how to register for training.

link to CLDT page

---

episodes/18-preparation.md

attempts to fix #1642 
I did something slightly different than the suggestion, but i agree there was a typo in the box. 
I think leaving it at the top actually makes sense for two reasons:
1. in theory, trainees are coming back to this page as a reference after the workshop more often than reading it when they would not know what we mean by cutting, and having a warning at the top of the episode that the version they saw in their workshop may have been truncated
2.  it serves as an additional reminder to trainers that this episode is a good place to make up time if needed. While a trainer would see the entirety of the episode while preparing, I think at the top it is more likely to catch & support in real time a new trainer who might be nervous; that is the note to cut from this episode …

Fix typo in cutting call out 

---

episodes/15-carpentries.md

Closes #1655
This adds a solution box to [the _Test yourself!_ exercise](https://carpentries.github.io/instructor-training/15-carpentries.html#test-yourself), containing links to the terms as defined in [the Community Glossary](https://github.com/carpentries/community-development/blob/main/glossary.md). (HT to @kariljordan for suggesting this approach.)
Please let me know if you would prefer the terms to be defined in the solution box itself: happy to update. My rationale for linking out was to avoid content rot as definitions diverge in the glossary.

add solution linking to glossary

---

episodes/15-carpentries.md

I ran a markdown link checker https://github.com/tcort/markdown-link-check and then confirmed by hand if any links were broken. I found one, which I fixed here!
Check results here [md-links.txt](https://github.com/user-attachments/files/15900541/md-links.txt) - quite a few false positives.

Fix link to https://www.liberquarterly.eu/article/10.18352/lq.10176/

---

episodes/15-carpentries.md

Adjust statement on commonality of lesson programs to indicate all share a "two to four day" format instead of just 2-day. This reflects current practice.

Add alternative to 2-day workshops

---

episodes/24-practices.md

Adds a link to Excalidraw (the same tool as the concept map exercise) in a hint. Wording maybe could be improved by someone else.

Add link to excalidraw for concept organizer exercise

---

episodes/15-carpentries.md

- Replaced "executive council" with governance and linked to governance page
- Minor grammatical revisions
Address #1673

Updates governance language under "how we operate"

---

episodes/01-welcome.md

The curriculum offers some resources about using pronouns.  The language "For those unfamiliar with..." reminds some users that there is a concept they are unfamiliar with, and does not seem to have any other purpose.  
I am recommending removing that language and only offering the resources.  If we are offering the resources, we should offer them as they are, without contextualizing that some people don't know about them.

remove dismissive language

---

episodes/15-carpentries.md

This PR attempts to address #1720 by updating the links to the lesson templates.

Update workbench lesson template links

---

config.yaml

Sets up the curriculum site to be tracked by our self-hosted Matomo web analytics platform.

Configure Matomo analytics

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/suggest_improvement_1_lesson.yml
.github/ISSUE_TEMPLATE/suggest_improvement_2_episode.yml
.github/PULL_REQUEST_TEMPLATE.md
CODE_OF_CONDUCT.md
episodes/01-welcome.md
episodes/08-motivation.md
episodes/09-eia.md
episodes/12-homework.md
episodes/14-checkout.md
episodes/15-carpentries.md
episodes/21-management.md
episodes/23-introductions.md
index.md
instructors/instructor-notes.md
learners/checkout.md
learners/training_calendar.md
registration_confirmation.md

Now that we have a redesigned [handbook](https://docs.carpentries.org/), this updates links throughout the IT curriculum.

update links to handbook throughout

---

learners/setup.md

Fix broken link in learner/setup.md

Fix report reference

---

config.yaml
instructors/instructor-notes.md
learners/training_info.md

(Tagging @carpentries/core-team-workshop-admin for review and discussion. Input also welcome from Trainers/others ❤️)
As discussed in previous Trainers meetings and internally with the Workshops and Instruction Team, this would replace the individual event websites that currently need to be built from https://github.com/carpentries/training-template.
You can preview what these changes look like at https://tobyhodges.github.io/solid-spoon/training_info.html
Some notes, relative to the current content in the training website template:
* Removes link to etherpad
* Assumes trainees will know who their Trainers will be, I guess from the initial info email they receive about the event (the one that links them to this page)?
* Removes the (commented out) suggested schedule table for a 4 half-day …

Add a general information page about the training

---

CONTRIBUTING.md
episodes/04-expertise.md
episodes/11-practice-teaching.md

I completed instructor training recently (it was _awesome_) and took some notes where I got briefly "stuck" and distracted reading the curriculum. More rationale in commit messages about the specific changes :)
As I was working on this I also noticed some links in `CONTRIBUTING.md` didn't behave as expected, and looking at `CONTRIBUTING.md` in other lesson repos, I think the preferred terminology changed from "master repository" to "upstream repository", so I got that while I was in there too.
Thanks all!
_If any relevant discussions have taken place …

Miscellaneous minor wording / emphasis / link changes

---

learners/checkout.md

Fix broken blog post link

---

episodes/01-welcome.md
episodes/02-practice-learning.md
episodes/05-memory.md
episodes/09-eia.md
episodes/11-practice-teaching.md
episodes/14-checkout.md
episodes/15-carpentries.md
episodes/17-live.md
episodes/20-performance.md
episodes/21-management.md
instructors/checkout.md
instructors/instructor-notes.md
learners/checkout.md

- Removes links saying `here`. As [they are not meanigful for screen readers](https://webaccess.berkeley.edu/ask-pecan/click-here)
- Converts plain links to meaningful hyperlinks

Basic accessibility changes

---

learners/checkout.md

Typo of Glosario (spelled with double "s") in the Carpentries Instructor Checkout Instructions page. I am making this change as part of my "Get Involved!" contribution for checkout.
<details>
For more guidance on how to contribute changes to a Carpentries project, please review [the Contributing Guide](CONTRIBUTING.md) and [Code of Conduct](https://docs.carpentries.org/policies/coc/).
Please keep in mind that lesson Maintainers are volunteers and it may be some time …

Glosario typo

---

episodes/15-carpentries.md

Update independence status

---

.gitignore
episodes/01-welcome.md
episodes/02-practice-learning.md
episodes/04-expertise.md
episodes/05-memory.md
episodes/06-feedback.md
episodes/08-motivation.md
episodes/09-eia.md
episodes/11-practice-teaching.md
episodes/13-second-welcome.md
episodes/14-checkout.md
episodes/15-carpentries.md
episodes/17-live.md
episodes/20-performance.md
episodes/21-management.md
episodes/23-introductions.md
episodes/25-wrap-up.md

This PR is focused on improving the clarity and consistency of links across the instructor training, particularly when used in exercises that may be copied into etherpads (and thus not copy links without explicit text). Additional changes are listed below and generally connect to the legibility of links for both disabled and non-disabled users (including screen-reader software).
Changes:
1. Replace `[Linkname][url] [url][url]` in exercises by adding the word `at` between linkname and URL to sound more natural but still provide information in an etherpad-friendly way
2. Add periods where natural after sentence-ending links
3. Adjust some formatting and caption for images to improve display and accessibility
4. Adjust link text when large portions of a sentence are linked to reduce …

Improve link display

---

episodes/15-carpentries.md

Resolves #1839 by adding some guidance for trainees, encouraging them to register their workshops teaching incubator/lab lessons.

guide trainees to register incubator/lab workshops

---

episodes/14-checkout.md

responds to a trainee question
(if accepted this should also get updated on the [etherpad template](https://pad.carpentries.org/ttt-template))

warn that there are no reminders in signup exercise

---

episodes/15-carpentries.md

closes #1896 
the editor tried to "help" when pasting a new URL and it ended up putting a md link in the URL for the reference

fix typo in link URL 

---

episodes/01-welcome.md
episodes/02-practice-learning.md
episodes/15-carpentries.md
episodes/18-preparation.md
episodes/21-management.md
episodes/23-introductions.md
episodes/25-wrap-up.md
instructors/instructor-notes.md
learners/checkout.md

**Summary**
- Standardize capitalization of role terms across the curriculum to match the style guide.
- Capitalize: Instructor, Trainer/Trainers
- Lowercase: helper(s), host(s)
- Updated headings, body text, and one image alt text
- No content/meaning changes
**Issue**
Closes #1843.

Standardize role capitalization

---

episodes/09-eia.md

We might want to use a different strategy for this though; the content was not moved so the "fix" is a webarchive link, but maybe we do not want to do that? 
closes #1869

Repair source for DEI glossary terms
