carpentries/instructor-training

11-workshop.md
Changes made to section 3. Multiple Choice Questions With Distractors in order to improve clarity.
=> Clarification of 11-workshop content

instructors.md
Will need to be expanded and written in better sentences.
=> adding logistics notes while they are fresh

00-introduction.md, 01-models.md, index.md
This PR is more for "provoking discussion" than it is "merge this in."  Would like to know if this is a sensible way to re-divide and organize information, or if I'm being overly pedantic.
=> restructuring first lesson and adding potential exercises and objectives

07-motivation.md
Adds more discussion and some links to further reading.
=> Filling in discussion of growth mindset and stereotype threat

07-motivation.md
=> Impostor syndrome

03-maps.md, 07-motivation.md
1.  Adding forward mention from 03-maps about the J word.
2.  Adding note to "Things you Shouldn't Do" about the J word with backward ref.
This closes #33.
=> Mentioning the J word

03-maps.md, 04-faded.md, 05-design.md, 07-motivation.md
While going through the material I stumbled upon a few minor issues and tried to fix them.
=> Fix minor typos

instructors.md
=> Notes for instructor's guide

01-introduction.md, checklist.md, index.md, reference.md
=> Phonic wholeword

02-terms.md
Looks like it was somehow scuttled when moving these materials from 01 to 02
=> This is #61 again.

instructors.md
=> A few big-picture ideas for trainers

01-introduction.md, 02-terms.md, 05-expertise.md, 06-memory.md, 09-motivation.md, 10-carpentries.md
I can change the comments to actual text that would show up on the web pages and be easier to find...let me know.
=> adding comments as placeholders for potential diagrams

07-design.md
The ACM page doesn't have a PDF, and someone might (erroneously) think that no 
PDF is available.
=> Link to the PDF of the Parnas/Clements article, instead of the ACM page.

instructors.md
=> Describing video recording exercise

Gemfile, index.md
=> Rewriting blurb

index.md, messages/checkout.txt, messages/welcome.txt
*  Fixes #92.
*  Depends on #133.
=> Make it clear that checkout happens after training, and synchronizing readings.

06-memory.md, instructors.md
This more-or-less corresponds to UW, with some Davis and Oklahoma mixed in.
@arokem @apawlik @ChristinaLK can you all please review?
This closes #38.
=> Revamping schedule

10-carpentries.md
=> Note on governance

08-practices.md
=> Fuller description of live coding exercise

08-practices.md
=> Expanding note on I/We/You

instructors.md
=> More notes on video recording

02-terms.md
addresses #44 
The "exercise" may be a little too meta...let me know if it's too much.
=> reworking info on situated learning

messages/outline.md, outline.md
Still needs revision - comments welcome!
Addressing point 6 in issue #83
=> adding beginning of outline for trainees to use during sessions

_episodes/14-carpentries.md
Uses direct quotes from SWC and DC sites.
Closes #36.
=> Explaining what costs what

_episodes/07-memory.md
=> Concept maps are good for more than just lessons

_extras/checkout.md
Closes #51.
Closes #52.
Closes #53.
Closes #54.
Closes #55.
=> Explaining what makes a good exercise submission

_episodes/03-coffee.md, _episodes/06-lunch.md, _episodes/08-coffee.md, _episodes/13-coffee.md, _episodes/16-lunch.md, _episodes/19-coffee.md
Some suggestions for things people can reflect on during the breaks.
=> Things to reflect on

_episodes/11-summarize.md, setup.md
=> Asking trainees to set up software

_extras/discuss.md
Closes #144 (at least partially).
=> Starting to keep score of what we don't do

_episodes/02-novice.md, _episodes/04-performance.md, _episodes/17-motivation.md, _episodes/18-objectives.md
Just some minor typo and link fixes.
=> Erinbecker fix links

CONTRIBUTING.md, _episodes/12-live.md, _extras/guide.md, index.md
Adding videos created by @lexnederbragt showing how to do live coding wrong, and how to do it right.
=> Live coding videos

_includes/carpentries.html, _layouts/lesson_homepage.html, index.md
Condensing + reorganizing the front page.  Attempting to make it less "wall-of-text"-y.
=> Front page edits

reference.md
Reformatting the reference guide to tidy up line wrapping, grammar, and spelling.
=> Reformatting reference

_extras/checkout.md
Per discussion with @tracykteal on Monday.
Prose is definitely "first draft" quality; feel free to edit sentences.  :)
=> Adding rationale for checkout steps

_episodes/14-carpentries.md
I think it's a typo, but maybe you're trying to be emphatic.
=> 14-carpentries.md: Remove extra '?' in 'questions'

_episodes/19-lessons.md
add a more specific "evaluate learning objectives" challenge
=> new challenge: concrete DC SWC learning objectives

_episodes/10-load.md
To get students a little familiar with our lessons and the make the faded example a little less scary, I have them pick block of code from a Unix or Python for loop lesson or the R ggplot lesson. This provide a little bit more cohesion among the learners. 
I chose for loops and ggplot because I'm familiar with those. Other instructor trainers could replace the examples with their favorites.
=> added a "fade a SWC block of code" challenge

_episodes/21-summarize.md
I tried to beef this section up since its so important. 
I added 
- some objectives and a questions,
- the new survey monkey link
- a little paragraph about thanks. 
I like to end by thanking everyone so they leave feeling good about themselves :)
=> added objectives, survey links, and thanks

_episodes/00-welcome.md
First attempt to address [issue #231](https://github.com/swcarpentry/instructor-training/issues/231) on adding a welcome episode. 
These are the first three multiple questions that come to mind. A variation of the 2nd is part of the post-workshop questionnaire. I'm open to adding more or rewording these or any other suggestions. 
Also, I call this lesson 00, but it could be 01, especially if the current episode one is moved to later.
=> Create welcome episode 00-welcome.md 

_episodes/01-introduction.md, _episodes/02-novice.md, _episodes/03-coffee.md, _episodes/04-performance.md, _episodes/19-lessons.md, _extras/checkout.md
Added DC lesson descriptions to 19-lessons to replace "FIXME".
=> Add DC lessons

_extras/guide.md
Files in the 'files' folder have moved to two separate subfolder, this updates the links to them
=> Fix links to files in 'files' that have moved

_episodes/12-summarize.md
Clarifying role of the instructor while collecting one up/down feedback.
=> Added instructor instructions for one up/down

_episodes/05-performance.md
Also, making the section on feedback less blog-posty and more formal.
=> addressing Lex's comments in #248

_episodes/13-live.md
* opening up for teaching something else than unix (bash) shell for loop
* adding preparing fellow trainee who will be watching
=> Improving live coding exercise description

_episodes/19-motivation.md
I found this definition more clear than the 'In brief,... ' sentence.
=> Added definition of stereotype threat

_episodes/19-motivation.md
A few of the links to other lessons were broken.
=> Fix broken links in Motivation and Demotivation lesson

CONTRIBUTING.md
An attempt to address #275 
- add steps of creating and cloning a fork
- change 'desktop copy' to 'local copy'
=> Elaborate on the GitHub flow

index.md
=> Linking to application form

_episodes/08-memory.md
An attempt to address #273 
I am new here, so please tell me if you prefer smaller or larger Issues / PRs, or if you omit Issues for rather smaller PRs.
The second commit (adding the example of giving directions including "where the gas station used to be") could be dropped, or the flow between the sentences improved.  I don't mind dropping it.
=> Driving example

_extras/checkout.md
Change DC github repo links to direct links
=> make links direct

_episodes/21-carpentries.md
Fixes small rendering issues in 21-carpentries page.
=> Add whitespace before bullet points.

_config.yml, _episodes/22-summarize.md, _extras/guide.md
1. Putting link to survey in configuration.
2. Adding survey link to checklist.
=> Emphasizing the post-workshop survey

_episodes/19-lessons.md
Under setion:  
Software and Data Carpentry Lessons
....
Sofware carpentry
....
The links for "Programming with Python" and "Version Control with Git" Site as well as Instructor guide were swapped in order to link to correct sites.
Ex: "Programming with Python" links ended up on the "Version Control with Git" sites and vice versa.
=> Updated links - Software Carpentry lessons (19-lessons.md)

_episodes/08-memory.md
=> Introducing (and partly debunking) the notion of reflective practice and the 10,000 hour rule.

_episodes/03-terms.md
It confused me, but maybe I am the only one.
=> Clarify that connectivism != connectionism 

_episodes/12-summarize.md
Giving space at the end of the day for people to reflect on what they learned.
=> Adding reflection

_episodes/05-performance.md
Addressing #311, this is what we used as length last time I did a TTT.
=> Add max length of first video

_config.yml
=> adding DC github url to config

_episodes/13-live.md
I suggest to first watch the two videos, collect and discuss feedback on them, and only *then* go over the top 10. Hopefully most of the items will have been treated by then.
=> Move watching the live coding videos before top 10

_episodes/19-lessons.md
=> Examples of learning objectives

_episodes/19-lessons.md
In preparing to teach this lesson, I had the idea to show the learners the lesson objectives of the lesson on lesson objectives, but then discovered these are not very well written :-) 
* makes the order more consistent with order of the lesson
* removes some phrasing not used (any more) in the lesson
=> Update lesson objectives of lesson on them

files/rubric.txt
This closes #336 and incorporates feedback given on that issue.
=> Rubric for scoring applications for open instructor training.

_episodes/12-summarize.md
I tuned this homework section into a callout section to make it stand out more. 
I added a homework assignment about preparing for live coding (since its not great when we forget to warn them about this)
=> homework update

_episodes/21-carpentries.md
=> Mentioning the no-show policy

_episodes/16-motivation.md
Closes #124 by putting stereotype threat discussion in a callout and mentioning challenges to it - @arokem @alistairwalsh @patitsas and others please comment.
=> Changing discussion of stereotype threat

_episodes/11-load.md
Given that the beginning of this lesson talks about "Extraneous load" I'm not really a fan of having the parson's problem challenge have an unnecessary line of code in it. So, I added a challenge question that is just about jumbling and un jumbling a problem.
=> second parsons problem challenge

_episodes/11-load.md
added two time suggestions based on @ErinBecker's teaching
=> add time suggestion

_episodes/08-memory.md
I added time suggestions and etherpad prompts based on the way @smcclatchy taught this
=> add time suggestion and etherpad prompt

_episodes/15-practices.md
This particular episode does not currently have any challenges or exercise. @ErinBecker used this in a workshop and it worked really well.
=> added a teaching practice discussion

_episodes/02-novice.md
added 1), 2), and 3) so that people can respond with 1 2 3 in the etherpad
=> made easier for etherpad discussion

_extras/checkout.md
As per agreement with Trainers group and Carpentry staff, a single checkout will now be required to certify for both Data and Software carpentry.
=> Change to single checkout

_episodes/16-motivation.md
=> Correct link to testimonials from instructors

_extras/guide.md
Addresses issue https://github.com/swcarpentry/instructor-training/issues/414, at least in the instructor notes
=> adds closed captioning to instructor notes

_episodes/01-welcome.md
Make the CoC the first thing we talk about so that people are aware of it before proceeding.
=> Add CoC to the beginning

_episodes/01-welcome.md
Expand the section on teacher introductions and student introductions. cc @tracykteal
=> expanded teacher and learner introductions

_extras/guide.md
I think we need to explicitly remind instructors to introduce themselves and each other.  How is this for a simple checklist @tracykteal ?
=> add instructions for introduction

_extras/checkout.md
Addresses https://github.com/swcarpentry/instructor-training/issues/356
=> reference lesson contribution guidelines

_episodes/19-lessons.md
Addresses https://github.com/swcarpentry/instructor-training/issues/406
=> Link lessons

_episodes/01-welcome.md, _episodes/02-novice.md, _episodes/03-terms.md, _episodes/05-performance.md, _episodes/08-memory.md, _episodes/10-performance.md, _episodes/11-load.md, _episodes/12-summarize.md, _episodes/13-live.md, _episodes/16-motivation.md, _episodes/19-lessons.md, _episodes/21-carpentries.md
Addresses https://github.com/swcarpentry/instructor-training/issues/382
=> Add timing

_extras/guide.md
Reverts swcarpentry/instructor-training#416
=> Revert "adds closed captioning to instructor notes"

_episodes/03-terms.md
Revised the section of PCK to be more brief and provide specific examples of each part that correspond to the Carpentries.
=> revision of the pedagogical content knowledge

_episodes/16-motivation.md
addresses #376
As a side note -- I wonder if this was deleted because some of it refer to aspects that aren't part of our workshops (rubrics/grading, specifically).  I think most of it is general enough to apply to our workshops, but only with some interpretation.
=> adding motivational list

_extras/introductions.md, files/intro-slides/slides.html, files/intro-slides/slides.md
1.  Import material on introductions from <https://github.com/tracykteal/instructors-introduction>.
2.  Move prose from `README.md` to `_extras/introductions.md`.
3.  Move slides to `files/intro-slides/*.*`.
=> Bringing in material on introductions from @tracykteal

_extras/checkout.md
Fixes https://github.com/swcarpentry/instructor-training/issues/411
=> Add exercise to create AMY account

_episodes/16-motivation.md
=> Fix typo in motivation episode

files/teaching-demo-rubric.md
Fixes https://github.com/swcarpentry/instructor-training/issues/394
This is just to get us started. Please feel free to add or change items as this is developed.
=> Add rubric suggestions

reference.md
Sitting in instructor training in Cape Town. I just read this book and thought that it was relevant to the "Expertise and Memory" session.
=> Added reference to "Moonwalking with Einstein".

_episodes/21-carpentries.md
Fixes https://github.com/swcarpentry/instructor-training/issues/454
=> update community section

_episodes/21-carpentries.md
=> update workshop coordinator contact

_episodes/21-carpentries.md
Fixes https://github.com/swcarpentry/instructor-training/issues/458
=> Add connection to NumFOCUS

_episodes/21-carpentries.md
=> remove "two day" from DC description (it's not a difference)

_episodes/21-carpentries.md
Most episodes should incorporate more than the one or two exercises recommended. More is usually better.
=> update exercise recommendations

_episodes/15-practices.md
=> Fixed spelling error under teaching practices discussion

README.md
Getting everything up to date.  :)  
@ErinBecker let me know if you want me to add the new instructors in this PR as well.
=> adding Erin as maintainer

_episodes/21-carpentries.md
Fixes https://github.com/swcarpentry/instructor-training/issues/453
=> add link to policies repo

_episodes/16-motivation.md
Fixes https://github.com/swcarpentry/instructor-training/issues/465
=> update never learn alone

_episodes/08-memory.md
Add Quora discussion for those interested.
Fixes https://github.com/swcarpentry/instructor-training/issues/443
=> add further reading for phone numbers

_extras/guide.md
=> Switching to Zoom

_extras/partner_policy.md, _extras/training_calendar.md
This lesson is currently being prepared for publication and is under development at https://github.com/ErinBecker/instructor-training-reorg/. Please submit any issues or PRs to that repo (not here).
=> Training calendar

_episodes/21-carpentries.md
=> Practice with infrastructure: need to include DC and SWC #459

index.md
This lesson is currently being prepared for publication and is under development at https://github.com/ErinBecker/instructor-training-reorg/. Please submit any issues or PRs to that repo (not here).
=> Fixed minor typo

_extras/checkout.md
"an Carpentry instructor" -> "a Carpentry instructor"
=> Minor grammar fix

_extras/partner_policy.md
=> Fix partner_policy.md

_episodes/15-live.md
Replaced recieved with received.
=> Fixed spelling error

_episodes/15-live.md
Good stuff Rayna - I have just fixed some issues. I also added 'use mouse to highlight' as I think that is effective
=> fixing typos and punctuation

_episodes/15-live.md
I would like to point the 5 attendees of today's demo session to a "top tips/guidelines" for live coding resources. But, I see that these are hidden as a solution in the lesson materials. 
http://carpentries.github.io/instructor-training/15-live/
I would like to make these more prominent somehow. So I thought they could go at the end. I reworded them a little for clarity in this stand-alone the section. But, I think there is room for clarity or maybe we can even add a few tips....
=> top 10 tips revisited

_episodes/03-expertise.md
Minor typo fix to add colon before start of list.
=> Added colon before start of list

_episodes/15-live.md
Thought that it would make sense to add emphasis given the mid-paragraph `:`
=> Add emphasis

_episodes/15-live.md
Reverts carpentries/instructor-training#532
=> Revert "Fix a broken link to another part of the lesson."

_episodes/05-memory.md
Use `.python` style for better formatting, use descriptive docstrings.
=> 05-memory.md: python formatting, docstrings

_episodes/01-welcome.md
Minor language correction, typo of grammar.
=> small conjugation correction

_extras/guide.md
Fixes https://github.com/carpentries/instructor-training/issues/499
=> Suggested episodes

_extras/checkout.md
Fixes https://github.com/carpentries/instructor-training/issues/501
=> change order of suggestions for lesson contribution

_episodes/08-motivation.md
As per https://github.com/carpentries/instructor-training/issues/551
=> add "don't take over keyboard"

_episodes/01-welcome.md
As per https://github.com/carpentries/instructor-training/issues/550
=> change K-12

_extras/guide.md
=> add email template for bilingual demo sessions

files/messages/checkout.txt
Copies wording introduced in #560 to checkout email
=> Update checkout email to reflect 'any order'

_extras/guide.md
=> added bilingual email for demos

_episodes/03-expertise.md
=> add examples of fluid representations

_episodes/11-practice-teaching.md
=> update instructions for teaching practice

_episodes/08-motivation.md
Now: http://carpentries.github.io/instructor-training/03-expertise/#limitations-of-expertise
=> Fix broken link.

_episodes/09-mindset.md
Re https://github.com/carpentries/instructor-training/issues/519
=> link to previous material

_episodes/02-practice-learning.md
Re: https://github.com/carpentries/instructor-training/issues/539
=> update timings for unix commands

_episodes/09-mindset.md
Re: https://github.com/carpentries/instructor-training/issues/518
=> Remove "official"

_extras/guide.md
Re: https://github.com/carpentries/instructor-training/issues/511
=> update zoom instructions

_episodes/19-introductions.md
Fixed broken link in 19-introductions.md
=> Fixed broken link in 19-introductions.md

_episodes/11-practice-teaching.md
This connects this paragraph to the previous and applicable mindset content. It also clarifies the use of the phrase "lesson study" here, which is different from how one might read the phrase casually.
=> Clarify "lesson study" header

_extras/guide.md, files/messages/welcome.txt
=> Fix more broken links

_episodes/08-motivation.md, _episodes/11-practice-teaching.md, _episodes/15-live.md, _episodes/19-introductions.md, _episodes/20-carpentries.md, _episodes/22-practices.md, _extras/checkout.md, _extras/guide.md, index.md, setup.md
=> Improve link labels

_extras/guide.md
Hi Karen feel free to reject my suggested changes
=> punctuation, another tip and save chat

_episodes/08-motivation.md
Consistently using graph instead of grid (see Think-Pair_share exercise below)
=> grid - graph

_episodes/14-lesson-study.md
See discussion in #630. This takes 10 minutes off this episode.
Also, adjusted key points to reflect what is in the episode
=> Removing section on "Adapting Challenges"

_episodes/01-welcome.md
Tracy is the E.D. of The Carpentries now:)
=> Updated Tracy's title

_episodes/09-mindset.md
=> Fixed typo

_episodes/08-motivation.md
If the image needs to be added as a png file instead of embedding it as a link, let me know and I'll fix that.
=> Added XKCD's imposter syndrome cartoon

bin/lesson_initialize.py
Sames as #646 plus subset of https://github.com/swcarpentry/lesson-example/pull/186.
=> Fix typos & hyperlinks

_episodes/19-introductions.md
Changed single paragraph with long list of questions as single block of text to bulleted list of questions.  I find this much more readable and easier to access.
=> Changed "Your Academic Past" for readailbity.

_episodes/02-practice-learning.md
I think it's more common to use the full name, followed by the last name in repeated use.
=> Small change in wording

reference.md
=> Fix hyperlink

_episodes/09-mindset.md
Per discussion in https://github.com/carpentries/instructor-training/issues/616
=> Replace mindset quiz with think-pair-share

_episodes/22-practices.md
per https://github.com/carpentries/instructor-training/issues/627
=> add link to troubleshooting page

_extras/guide.md
=> updated trainer agreement link

_extras/checkout.md
Addresses https://github.com/carpentries/instructor-training/issues/684#issuecomment-389567637
=> Makes need to email checkout more clear

_episodes/14-lesson-study.md
=> added question mark to question

_extras/guide.md
https://github.com/carpentries/instructor-training/issues/652
=> Add post-surveys to post-email template

_episodes/03-expertise.md
=> Clarifying point in expertise

_extras/guide.md
tips for
- supporting lead instructor
- general online exercise management
Addresses #664
=> online teaching tips

_extras/guide.md
Adding @anenadic 's google doc in its new official home!
=> Add Google Doc template link to instructor notes

_extras/checkout.md
=> Fix broken contact links in checkout.md

_episodes/22-practices.md
@karinlag See change made in instructor training.
=> Renamed Policy Subcommittee to Code of Conduct Committee

index.md
Addresses https://github.com/carpentries/instructor-training/issues/751 . Thanks @erjank !
=> Fix CoC link

_episodes/19-introductions.md
minor fix, the list at the top didn't match the headings
=> make intro list match subheadings

_extras/checkout.md
This list is really out of date. We accept contributions to all lessons of the types listed in this document.
=> remove list of lessons to contribute to

_episodes/23-checkout.md
=> Remove outdated link

_episodes/08-motivation.md
@ChristinaLK Solves this https://github.com/carpentries/instructor-training/issues/739
=> Update link to Shapiro-nuberg pdf

_episodes/22-practices.md
In response to this issue: https://github.com/carpentries/instructor-training/issues/743
@raynamharris @ChristinaLK
=> Solution made list

_episodes/01-welcome.md
Minor typo correction: the word 'the' was duplicated.
=> Duplicated word

_episodes/01-welcome.md
As per issue https://github.com/carpentries/instructor-training/issues/769
Now, I really do believe this challenge will table about 3 minutes
(Also, when you look at the diff, I did not accidentally delete part of question 2; it appears at the end after the deletion block)
=> remove MCQ 3

_episodes/14-lesson-study.md
Adds the output of the R code so that this challenge is more accessible to people who don't code with R on a regular basis as per #772
=> add out challenge output

_extras/about.md, _extras/checkout.md, _extras/glossary.md, _extras/guide.md, _extras/icebreakers.md, _extras/members.md, _extras/training_calendar.md
=> removing permalink from extras pages

_extras/checkout.md
=> Email address fix

_episodes/05-memory.md
=> new memory test link

_episodes/20-carpentries.md
Minor correction: "Each project will maintain their own" should now be "Each project maintains its own".
=> Grammar correction (tense + person)

_episodes/05-memory.md
Addresses https://github.com/carpentries/instructor-training/issues/797
=> Update memory exercise to match new link

_episodes/02-practice-learning.md
Noticed a tiny error while running through the page.  Otherwise looks great!
=> Small grammatical error

_episodes/01-welcome.md
=> Reorganize Overview to describe what Instructor training IS first, before

_episodes/20-carpentries.md
Note that this goes with the new handout and is not correct for the handout currently linked. This PR should be merged with the handout update to make sure these match. #784
=> added solution to new matching exercise

_episodes/15-lesson-study.md
fixes typos, adds link to Tractenberg debrief as attribution for "grow a level."
=> fixes and link

_episodes/20-carpentries.md
Added DC and SWC missions as per #785 . This doesn't add a a challenge exercise as suggested, but it does provide a little more meat in the opening paragraph. 
One thing to consider is rewriting this whole episode. I think the venn diagram and some of the lists could be condensed into 1 table, for example.
=> add DC and SWC mission

_episodes/05-memory.md
relates to https://github.com/carpentries/instructor-training/issues/811
=> shave 5 min off memory episode

_episodes/02-practice-learning.md, fig/mental_models.svg
=> Adding svg version of mental models diagram from @amyehodge

_episodes/21-carpentries.md
- Update link to current version of roles worksheet handout
- Update LC 'must include' language and link to core lessons
=> Update (LC) content and links

_episodes/24-practices.md
A trainee at today's workshop inspired me to suggest writing this out.
=> Explain abbreviation

_episodes/09-mindset.md
I think this bold formatting wil make it easier to answer the challenge question about the types of praise.
=> add bold formatting to 3 types of praise

_episodes/08-motivation.md
This was originally called . "one thing" which wasn't super descriptive. So, I revamped the name and added a link to the main webpage for the UK home office.
=> improve accessibility exercise name

_extras/guide.md
based on discussion at trainers meeting
=> adding note about breaks

_episodes/09-mindset.md
=> Removing non-applicable research link

_episodes/15-lesson-study.md
=> Fix for Dunning-Kruger effect link issue #875

_episodes/21-carpentries.md
Add a sentence and a keypoint about the handbook. Related to https://github.com/carpentries/instructor-training/issues/867
=> link to the carpentries handbook

_extras/checkout.md
Updating a typo and adding https to the name in the links
=> updating typo

setup.md
Taking a stab at https://github.com/carpentries/instructor-training/issues/899 using lessons from https://docs.carpentries.org/topic_folders/instructor_training/trainers_guide.html#starting-points-for-demos
=> Add LC to setup

_episodes/15-lesson-study.md
add note that the configuration problems and solutions page is linked from workshop pages, so instructors will know how to find it again
=> minor text addition re: problems & solutions

_episodes/05-memory.md
=> adding example solution to faded example exercise

_episodes/21-carpentries.md
Addresses https://github.com/carpentries/instructor-training/issues/906
=> Correct general carpentries descriptions in Ep 21

_episodes/03-expertise.md
Addresses https://github.com/carpentries/instructor-training/issues/913
=> Add chemistry fluid representation

_extras/members.md
=> Change wording of breaks

_episodes/18-management.md
not being comfortable teaching is hardly the only motivation - sounded a bit dismissive to me, therefore I would like to propose this small change in phrasing
=> re-phrasing

_extras/registration_confirmation.md, _includes/navbar.html
=> Hide registration

files/rubric.md
based on upcoming curriculum development
=> update to add +1 for Chemistry

_episodes/05-memory.md
This relates to issues #540  and (partially) #940 
I've updated online memory test to use the one created by @miku and separated the exercise into online and in person.
=> update online memory quiz and format of exercise

_episodes/17-performance.md
=> clarifying which rubric is being used for 2nd live coding

_episodes/11-practice-teaching.md
=> clarifying initial teaching exercise

_extras/training_calendar.md
Addresses https://github.com/carpentries/instructor-training/issues/912
=> Add start time links & clarification language

README.md
I replaced @ErinBecker's name with my name.
=> updated list of lesson maintainers

_episodes/20-checkout.md
=> Added demo rubric to checkout process page

_extras/checkout.md
=> Added suggested rubric to checkout process

_episodes/20-checkout.md, _extras/checkout.md
adds link to the checkout guide to the two locations, closes #957
=> add guide to checkout episode and checkout guide

_episodes/12-homework.md
=> adding keypoints to day 1 homework

_extras/checkout.md
This is a proposed fix to issue #907
=> Updating teaching demo lang

_episodes/13-second-welcome.md, _episodes/14-live.md, _episodes/15-lesson-study.md, _episodes/17-performance.md, _episodes/18-management.md, _episodes/20-checkout.md, _episodes/23-introductions.md, _episodes/24-practices.md
=> adding day 2 transition sentences

_extras/guide.md
=> adding note about day 2

_episodes/20-checkout.md, _extras/checkout.md
adds a note about how long it takes to get a certificate, as suggested by @ErinBecker in #986
=> add checkout timeline

_episodes/11-practice-teaching.md
these are sort of (?) major changes, so feel free to veto.
=> rearranging teaching feedback section

_extras/guide.md
This can & should be linked from the handbook demo section, but I decided that Instructor Notes was the best place to collect this, as we can continue to collect initialed "I like to x" style contributions as opposed to codifying things (as implied by handbook additions).
=> Add demo tips

_episodes/20-checkout.md, _episodes/21-carpentries.md
I added the pad of pads as a callout in the checkout section, inspired by @DanielleQuinn's choice to introduce it there in our workshop this week. 
and added how to create an etherpad to workshop setup.
=> Add etherpad info to the lesson 

_episodes/02-practice-learning.md, _episodes/03-expertise.md, _episodes/05-memory.md
@raynamharris @karenword may be worth scheduling another longish call to discuss this and the other one.
=> smoothing #1: how learning works

_extras/guide.md
Episode order section had several typos. I think this fixes them.
=> fixes several typos

_episodes/01-welcome.md, _episodes/02-practice-learning.md, _episodes/03-expertise.md, _episodes/08-motivation.md, _episodes/09-mindset.md
I tried to tweak these to make them a little closer to the reality that I've experienced. I also optioned out a couple of activities that tend to get cut for time. I'm sure others manage time differently, but I think this is at least a little more honest while leaving discretion for adjustment to the Trainer.
=> Timing adjustments

_extras/demo_lessons.md
Adds an note in general, not just to this lesson, that trainees can continue to the next episode on if they have a very short episode.
=> suggestion  to fix #972

_extras/demo_lessons.md
Change the page title from "Suggested Episodes for Teaching Demonstrations" to "Suggested Lessons for Teaching Demonstrations"
=> change the page title

_extras/checkout.md
This PR polishes the text in part 3 of the checkout.
=> Part 3 in checkout: add missing words

_extras/guide.md
does this sufficiently address issues #614 and #615? I took comments from both and created a section in the instructor guide about using Etherpad in the classroom
=> add etherpad to instructor notes

_episodes/14-live.md
=> Add note about red/green sticky notes

_episodes/20-checkout.md
We've had some misconceptions about the time frame coming through checkout, and I noticed that we don't currently have any information on this page to make that clear.
=> Add time frame for checkout

_episodes/11-practice-teaching.md
This make it explicit that somebody should be responsible for time keeping during the teaching exercise. 
This needs also equilateral modifications in the etherpad template.
=> Add person for timekeeping

_episodes/21-carpentries.md
Removes the requirement for reporting attendance, as per discussion in https://github.com/carpentries/instructor-training/issues/1021
=> remove attendance requirement in how we operate

_extras/demo_lessons.md
this lesson is discussion-based, so I'm changing the recommendation, as brought up by @masamiy  in https://github.com/carpentries/instructor-training/issues/1039.
cc @hoytpr @ErinBecker
=> update suggested genomics lessons for demos

_episodes/21-carpentries.md
Added links to Handbook in Key Points too so people can refer to them more easily.
=> Added links to Handbook in Key Points

_episodes/09-mindset.md, _episodes/23-introductions.md
Extra blank line had messed up the rendering of the exercise.
=> Ep11: Fix formatting of exercise block

_episodes/01-welcome.md
i think this will work to fix https://github.com/carpentries/instructor-training/issues/1051
=> fix link to icebreakers

_episodes/12-homework.md
Fix link to python loop episode
=> Fix link to python loop episode

_episodes/20-checkout.md
=> Fix rubric link

_extras/checkout.md
continuing https://github.com/carpentries/instructor-training/pull/1050/files
=> good first issue link goes here too

_extras/training_calendar.md
Publishes dates and registration information for events from January - April 2020
=> New calendar

_extras/icebreakers.md
I used a "What's your name and favorite emoji" ice breaker after the morning break on Day 1, and it worked very well!
=> add new icebreaker

_episodes/23-introductions.md
Swap out the cucurbits for titans of industry.
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The Carpentries Team at …
=> Swap out the cucurbits for titans of industry.

_episodes/03-expertise.md
objectives and keypoints were not updated yet
=> more updates of expert blind spot to awareness gap

_extras/etherpad.md
make sure we ask participants their pronouns when signing in in the Etherpad, and make clean we don't require them to share their email address with everyone publicly.
=> add pronouns to sign in, make email optional

_episodes/01-welcome.md
make formatting consistent across bullet points
=> fix missing period

index.md
Not sure why that phrasing was there
=> Remove "of course"

_extras/figures.md, _includes/manual_episode_order.html
Brings the latest version of the script to render all images in a page.
=> [fix #1106] upgrade to latest script to include figures

_episodes/01-welcome.md
=> fix duplicated word

_episodes/01-welcome.md
per discussion prompted by @angela-li and technique demonstrated by @lexnederbragt
=> Add Exercise for Preferred name and pronouns in welcome

_episodes/01-welcome.md
* using "preferred" isn't recommended
* add wording to make sure we don't force people to share their pronouns if they don't want to do it
=> make sharing pronouns more inclusive

_episodes/03-expertise.md, _episodes/24-practices.md
I finally did an offline exhaustive search to find the remaining occurrences of blind spot.
=> exhaustive search replacement of blind spot. closes #1079 

_episodes/21-carpentries.md
=> remove attendance policy

_extras/checkout.md
Line 127 said, "These sessions gives you a chance...". I changed gives to give.
=> Typo on line 127

_extras/demos_rubric.md
As discussed in issue #1133 I updated the language around passing demos and added another line to the rubric about typing out all of their code.
=> Updates to teaching demo rubric

_episodes/02-practice-learning.md, _episodes/03-expertise.md, _episodes/05-memory.md
When prepping to teach this week, I wrote out my own goals / learning objectives and am adding them to the episodes.
=> adding learning objectives to early episodes

_episodes/21-carpentries.md
Addresses https://github.com/carpentries/instructor-training/issues/1143
=> fix policies links

_extras/guide.md
I have used this list of questions for two training events and it has been very useful for us as Trainers to prepare to teach, and be sure our expectations of each other are clear.
=> suggested questions for Trainers to prepare to co-teach

_episodes/09-mindset.md
This sounded very unnatural (at least to a UK audience).
It also contrasts nicely with the previous example, and shows the subtle difference in language promoting different mindsets.
=> Use more realistic praise example

reference.md
The article was earlier redirected to the preprint version and the changes have been made to point towards the published version.
=> updated the article link

_extras/checkout.md
I personally feel that providing an example for a lesson and segment, in the context of teaching demonstration task, would provide clarity to the instructors-in-training. At the moment, there is a scope to get confused between lesson and segment terminology, especially for the members outside the Carpentries community.
=> Provided an example for the teaching demonstration

index.md
Added "Library Carpentry" to text
=> Added "Library Carpentry"

_episodes/05-memory.md, setup.md
Cleaning up old branches & found this... worth merging?
=> Karenword online alts

_extras/training_calendar.md
Adds new online events October/November 2020
=> Oct nov 2020 events

_episodes/02-practice-learning.md, _episodes/09-mindset.md
change quote tags to add styling
=> change quote tags to add styling

_episodes/08-motivation.md
Adds descriptive alt text for the two images in the motivation and demotivation episode.
=> add descriptive alt text to motivation episode

_episodes/01-welcome.md, _episodes/02-practice-learning.md, _episodes/03-expertise.md, _episodes/05-memory.md, _episodes/06-feedback.md, _episodes/08-motivation.md, _episodes/11-practice-teaching.md, _episodes/12-homework.md, _episodes/13-second-welcome.md, _episodes/14-live.md, _episodes/15-lesson-study.md, _episodes/20-checkout.md, _episodes/21-carpentries.md
Update things to be consistent with our style guide
=> style guide consistency

_extras/icebreakers.md
Had a teaching demo where my icebreaker "one good thing" went a bit subpar - and had one of the trainees (Simon Willison) suggest an absolutely AMAZING one: *What is a mythical creature from where you grew up?*
This is likely to be *so good* and also so much less "risky" in the time of COVID than the "one good thing" one!
=> Added absolutely brilliant icebreaker from Simon Willison

_episodes/14-live.md
Quickly added a line about the recent paper Carpentries instructors published related to the ten tips section.  Feedback and language changes welcome and encouraged!
=> Add link to paper with live coding tips

_episodes/20-checkout.md, _episodes/21-carpentries.md
=> more information about the lesson incubation

_extras/training_calendar.md
Please delete this line and the text below before submitting your contribution.
---
Thanks for contributing! If this contribution is for instructor training, please send an email to checkout@carpentries.org with a link to this contribution so we can record your progress. You’ve completed your contribution step for instructor checkout just by submitting this contribution.  
Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all contributions can be incorporated into the lesson materials, we appreciate your time and effort to improve the curriculum.  If you have any questions about the lesson maintenance process or would like to volunteer your time as a contribution reviewer, please contact The …
=> Close Jan 21-22 Registration

_episodes/21-carpentries.md
to fix rendering error and broken links
=> fix mssing url

_episodes/05-memory.md
It appears that his blog moved from `thing.html` to `thing/index.html`.
=> Update broken URL for Greg's post

_extras/training_calendar.md
=> Closed Feb 25-26 event

_extras/training_calendar.md
=> Closed March 3-4 event

_extras/training_calendar.md
publishes online instructor training workshops April-June 2021
=> Calendar 2021 q2

_extras/demo_lessons.md, _extras/members.md, _extras/training_calendar.md
Adds new events to instructor training calendar
=> New events

_extras/training_calendar.md
Publishes online instructor training events for 2021 Q3
=> Calendar 2021 Q3

_extras/training_calendar.md
=> fix line break

CITATION
=> Update citation 

_episodes/14-checkout.md
Thanks to @jporton for the catch!
=> update email and add mailto link

_extras/icebreakers.md
Two great ones I've learned from @ha0ye and @ChristinaLK recently :)
=> Add more icebreakers

_extras/registration_confirmation.md
=> update confirmation page link

_episodes/15-carpentries.md
=> Correct sentence

_episodes/01-welcome.md, _episodes/02-practice-learning.md, _episodes/04-expertise.md, _extras/guide.md
Each (type of) change has its own commit, so they can be easily be removed, if reviewers disagree.
Each change adds, removes, or changes at most a handful of words.
=> Various small corrections

_extras/checkout.md
=> clarify language re profile creation

_episodes/02-practice-learning.md
=> Removed superfluous blank character

_extras/training_calendar.md
posts training events for 2022Q2
=> Calendar 2022q2

_episodes/09-eia.md
Accommodation has to m's
Missing i in individual
<details>
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please …
=> Spelling errors

_extras/checkout.md
thanks to @cknuepfer via [comment on the pr that introduced this error](https://github.com/carpentries/instructor-training/pull/1293#pullrequestreview-901322002)
=> remove double word

_extras/checkout.md
This resource has moved to the incubator
=> update GitHub guide link

_episodes/05-memory.md
=> Fix for cognitive load theory hanging sentence and link

_episodes/18-preparation.md, _episodes/21-management.md
=> Move minute card from before break to before lunch

_episodes/12-homework.md
Fix the URL for [Repeating Actions with Loops in Python](https://swcarpentry.github.io/python-novice-inflammation/05-loop/) in Wrap-Up and Homework
=> fix: modify broken URL in episode 12

_extras/training_calendar.md
Rescheduling based on email from Trainers to Maneesha
=> reschedule Australia June 2022 training

index.md
On line 17, and Unix shell between R and python programming, as part of what is not taught in programming.
#checkout_process
<details>
about the lesson maintenance process …
=> note shell is not taught

_includes/syllabus.html
=> fix duplicate syllabus line

_episodes/01-welcome.md
<details>
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at …
=> SlightChangeInWording.md closes #1361 

_extras/guide.md
per @Denubis [suggestion](https://github.com/carpentries/trainers/pull/126/files#r798188899) in it curriculum policy review
=> add suggestion to  fork repo during prep

setup.md
...removing superfluous parentheses
=> Improve formatting

_episodes/18-preparation.md, _episodes/23-introductions.md, _extras/etherpad.md, _extras/guide.md
=> Always capitalize Etherpad

_episodes/21-management.md
=> Fix conjugation

_extras/checkout.md
=> correct link syntax

_extras/demo_lessons.md
These starting points for _Foundations of Astronomical Data Science_ have been approved by @carpentries/core-team-curriculum.
If and when this is merged, I will communicate the addition of a new lesson for teaching demos to the Trainer community.
=> add demo starting points for DC Astronomy

_episodes/14-checkout.md
closes #1404 per the great advice from #1395
=> add an option to the scheduling exercise

README.md
@karenword please review and merge
=> add new Maintainers

_extras/checkout.md
Updates information on AMY setup and login to refer to handbook page, reducing need for duplicate maintenance. Addresses and closes #1354
=> Refer to handbook for AMY information

_episodes/01-welcome.md
This uses text mostly from a [PR to Data lessons](https://github.com/data-lessons/instructor-training/pull/111) @pachadotdev and should close #1222 
It also relates to #1409
=> expand pronoun explanation and add resources

_episodes/13-second-welcome.md
Adds link to Workshop FAQ to help trainers answer questions and provide reference to new instructors later. Closes #1285
=> Add workshop FAQ callout

_episodes/14-checkout.md
(Also removes reference to bonus modules as these are not currently being offered.)
=> unified badge language

_episodes/09-eia.md
Updated alt text, contributed by Danielle Sieh for https://carpentries.github.io/instructor-training//fig/sketchplanations-the-curb-cut-effect.png
=> updated alt text

setup.md
Link was broken. Also corrects name.
=> Correct link for DC OpenRefine suggested lesson

_config.yml, _includes/check_transition_variables.html, _includes/lesson_footer.html, _includes/life_cycle.html, _includes/navbar.html, _layouts/base.html, assets/css/lesson.scss, bin/boilerplate/_config.yml
This pull request does two things:
1. It brings in the updates from styles since February
2. It sets the `_config.yml` variables needed to display the beta phase banner that points to https://preview.carpentries.org/instructor-training
I apologise for being late on this. I had to take some unexpected time off last week and was not able to get things in order until now. 
This will address #1396
=> Update Styles and Enter pre-beta stage of Workbench Beta Phase

_episodes/12-homework.md
Pushing this update on behalf of another member of the community as a lesson contribution
=> Non-working link to "Faceting in Open Refine"

_episodes/12-homework.md
I made a mistake and merged PR #1465 without applying @ndporter 's suggestions
=> actually apply the fix the previous PR comments suggested

_extras/training_calendar.md
<details>
about the lesson maintenance process or would like to volunteer your time as a contribution
reviewer, please contact The Carpentries Team at …
=> Closed 2023-01-19-ttt-online-EST

_extras/demo_lessons.md
**Wait to merge until the curriculum has been published.**
=> add starting points for DC Image Processing

episodes/23-introductions.md
=> fix internal link to icebreakers

episodes/02-practice-learning.md
Copied from existing Instructor Notes page (should also delete from notes file but let's see how this works first)
=> Add in-line note re concept maps

learners/training_calendar.md
@zkamvar This is a PR that we need to put through to the Styles version. Can you help?
=> Closing events on 15 and 21 Feb

learners/training_calendar.md
@zkamvar Here is another change to the calendar that needs to get moved to the styles version. Thanks!
=> Closed 2023-03-14-ttt-online-GMT

instructor-training.Rproj
This will allow RStudio users to double click on this file to open RStudio inside of this directory.
=> add rstudio project file

episodes/01-welcome.md
=> inline instructor note for captions,

episodes/23-introductions.md
Small addition to objectives of introduction  in episode 23 - awareness of the schedule.
=> Small addition - awareness of the schedule

index.md
Schedule is only in the instructor view
=> Removed note about schedule

README.md
Tim is stepping away temporarily from this role.
=> Remove Tim from Maintainers

learners/demos_rubric.md
I think fixes, things, but also I wonder if this should have been a relative link that is rendered, instead of typed out this way.
=> fix url closes #1546

learners/reference.md
I am submitting a revision based for checkout.  I added the Japanese word for lesson study.
=> revise jugyokenkyu entry.md

episodes/12-homework.md
Closes #1569 by updating name and link for OpenRefine suggested lesson in https://github.com/carpentries/instructor-training/12-homework
=> Correct link in 12-homework.md

learners/checkout.md
The sentence expresses everything it previously did with fewer words.
=> Remove duplicate “in-person” and unnecessary “special”

episodes/23-introductions.md
Closes #1478. Fix typo in first paragraph and split paragraph in 2 for readability.
=> Fix typo in 23-introductions.md

README.md, episodes/09-eia.md, learners/checkout.md
Update all slack links to new slack URL and invite link.
=> Update slack links

learners/training_calendar.md
Publishes 2023 Q4 training calendar
=> 2023 Q4 calendar

learners/training_calendar.md
@karenword or @maneesha can you double check the times and merge if correct? Thanks!
=> Added 2023-11-20-ttt-online-jena event

episodes/21-management.md
Closes #1506. Add an instructor note with some suggestions to get discussion started on challenges of having learners at different levels.
=> Add instructor note with suggestions for Sticky situation

episodes/08-motivation.md
A suggestion to replace confusing (to me) "rescue" metaphor in sentence on managing motivation with more direct language.
This one may just be me but it takes me a minute to process the sentence 
> What is important is to be mindful of times when your content is not motivating, and to strategize your rescue using some of the other techniques in this section.
because the word rescue throws me off, plus I don't think it always needs something as dramatic as rescue. I suggested some new language that is more direct and to me, less confusing.
=> Clarify wording on recovering motivation

episodes/02-practice-learning.md
=> Remove common word

learners/training_calendar.md
=> Remove Nov 20 event

learners/checkout.md
This is a start at incorporating the new video!
=> Add callout with demos video

episodes/01-welcome.md
Add instructor note discussing more options for inviting learners to get to know one another, as well as highlighting needs to potentially hear names pronounced and to balance time needs.
=> Add instructor note on learner introductions

learners/checkout.md
Note: this will have to be done each year as long as there are new Etherpads
=> Update welcome sessions Etherpad link

learners/training_calendar.md
=> Closed 2024-02-01-ttt-online-est

learners/training_calendar.md
=> Closed 2024-02-07-ttt-online-MST

episodes/01-welcome.md, index.md
Added links to the new CLDT curriculum ,replacing some links to the lesson dev study groups.
=> Added links to CLDT

learners/training_calendar.md
=> closed March 4-5 training

episodes/08-motivation.md
Relative link to episode 4 still used old format and was invalid.
=> Correct bad link in 08-motivation.md

LICENSE.md
=> Changed to HTTPs instead of HTTP

learners/demo_lessons.md
tiny fix based on a warning thrown by autochecks on another PR
=> fix missing s, resolve warning

learners/checkout.md
Added the AMY portal link to the "Get Involved" step for clarification on where to go.
<details>
Please keep in mind that lesson Maintainers are volunteers and it may be some time before they can respond to your contribution. Although not all …
=> Update checkout.md to include AMY link

learners/demos_rubric.md
Closed dangling markdown tag ( ** ) 
No issue previously opened
=> close markdown in new instructor training rubric notes sample

learners/checkout.md
I want to also confirm that this is the way that we want the policy stated, so tagging @carpentries/trainers-leadership for confirmation
=> clarify welcome step, closes #1677

index.md
Add missing link when release history is referenced.
=> Add release history link

README.md
remove @dpshelio as Maintainer on his request
=> remove maintainer

episodes/04-expertise.md
Remove trailing slash that breaks a link
=> remove trailing slash

episodes/05-memory.md
Remove trailing slash that breaks a link.
=> rm trailing slash

episodes/09-eia.md
Replace broken link. Closes #1699
=> Fix Pittsburg DEI glossary link

episodes/09-eia.md
Link to contribute on GitHub is to "edit" not "improve"
=> "edit" not "improve"

learners/demos_rubric.md
Say "asked to repeat" instead of "failed" teaching demo.
=> Ask to repeat, not fail

episodes/18-preparation.md
fixes #1718 + a couple other occurrences in this episode which seem to be loaded
=> correct use of "lesson"

learners/training_calendar.md
Remove 2024-09-10-ttt-online-AEST
=> remove 2024-09-10-ttt-online-AEST

learners/training_calendar.md
=> Remove 2024-09-26-ttt-online-EDT

learners/training_calendar.md
=> remove training

episodes/08-motivation.md, episodes/11-practice-teaching.md
Fixes small typos and replaces the J word term for readability.
=> Small typo fixes and some minor rewordings

learners/checkout.md
@sheraaronhurt you can merge whenever
=> Updated 2025 etherpad links

episodes/15-carpentries.md
Link is case sensitive - does not work with capital case
=> Fix blog post link

learners/training_calendar.md
Adds new Instructor Training event
=> add event 2025-03-03-ttt-online-UTC

learners/training_calendar.md
=> Remove ITT

episodes/23-introductions.md
Add explicit reference to Code of Conduct in solution list for what should be in an introduction challenge.
=> Add CoC reference to introductions challenge

episodes/23-introductions.md
Clarify what items in introductions challenge are sub-points and add additional timing guidance.
=> Clarify introductions challenge details

episodes/23-introductions.md
=> add spaces

episodes/12-homework.md
=> update languge for 4 day

episodes/25-wrap-up.md
=> etherpad tip closes #1874

episodes/02-practice-learning.md
Replace semi-colon with colon for emphasis
=> syntax update for emphasis 

episodes/05-memory.md
=> improve alt-text

episodes/21-management.md
I put it in as an instructor note, but we could also revise it into the challenge box.  I just figure that already has. alot of options and is sort of hard to parse
=> Direct people to website skill ups, closes #1884

learners/training_calendar.md, registration_confirmation.md
added information to complete the ITT application before attending training.
=> Add ITT application form

episodes/06-feedback.md, episodes/18-preparation.md, instructors/instructor-notes.md
- **fix minute card links, closes #1829"**
- **adjust language for online closes #1830 + another occurence**
=> Accomodate virtual minute cards
